In [1]:
print("Hello World")

Hello World


In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [15]:
import numpy as np

In [26]:
list=[[1,2,3],[1,2]]
nl=np.array(list)
print(type(nl))

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [18]:
nl

array([1, 2, 3])

In [19]:
nl.shape

(3,)

In [10]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])

In [11]:
arr[3:]=100

In [12]:
arr

array([  1,   2,   3, 100, 100, 100, 100, 100, 100, 100])

In [13]:
arr1=arr

In [16]:
arr1[3:]=500

In [17]:
arr

array([  1,   2,   3, 500, 500, 500, 500, 500, 500, 500])

In [18]:
arr2=arr.copy()

In [19]:
arr2[3:]=30

In [20]:
arr2

array([ 1,  2,  3, 30, 30, 30, 30, 30, 30, 30])

In [21]:
arr

array([  1,   2,   3, 500, 500, 500, 500, 500, 500, 500])

In [3]:
print(np.__version__)


2.3.5


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [10]:
s="str"
for i in "str":
    print(i,end=",")

s,t,r,

In [12]:
   a=[1,2,34,0]
   print(a[0])

1


In [ ]:
import numpy as np
